### ISSUE TITLE
Mirror内容不全

### ISSUE THREAD

**Issue by JustinAsdz** [AmazingAng/WTF-Solidity#194]

**Comment by AmazingAng** [comment]
对 mirror的编辑和github不太一样 挺多没有更新的地方 主要是图片格式 有什么好办法么

**Comment by JustinAsdz** [comment]
刚看到回复😂 感觉这个还是需要定期来更新下

mirror能直接链接到github的图片的话，那直接用git上的就行 这样应该比较方便

**Comment by AmazingAng** [comment]
好的  mirror还用不了github的图片 所以还挺麻烦

**Comment by XdpCs** [comment]
需要社区有人去调研 能够定时同步mirror的脚本

**Comment by shengxj1** [comment]
图片其实可以用脚本试一下
比如 13_Inheritance目录下面的 readme.md
图片链接用的是 ![13-1](./img/13-1.png)
可以算出路径是 13_Inheritance/img/13-1.png
可以用代理 cdn 拼出可访问的图片地址

https://cdn.jsdelivr.net/gh/AmazingAng/WTF-Solidity/13_Inheritance/img/13-1.png

![](https://cdn.jsdelivr.net/gh/AmazingAng/WTF-Solidity/13_Inheritance/img/13-1.png)

**Comment by XdpCs** [comment]
感谢你的贡献 我会去测试一下
