### ISSUE TITLE
第十二讲演示部分有疑问

### ISSUE THREAD

**Issue by buttonwild** [AmazingAng/WTF-Solidity#210]
1. 在etherscan上查询事件中的链接，使用的账号与上面步骤的数据不一致。
2. 在自己测试中，数据不能实时上链查询，是否和出块事件间隔有关系？

**Comment by AmazingAng** [comment]
1. 是的 这个etherscan的截图是贡献者后补的 后续会更新下 让两个截图一致
2. 交易在链上确认，再到etherscan同步需要时间

**Comment by buttonwild** [comment]
finished
