### ISSUE TITLE
第3讲函数类型，“调用pure跟view的函数是不需要付gas”的说法不妥，容易误导初学者

### ISSUE THREAD

**Issue by CryptoRbtree** [AmazingAng/WTF-Solidity#226]
调用pure跟view的函数是不需要付gas，是因为如果我们只想调用pure/view查数据，不需要上链，所以才不需要gas。
但是如果对pure/view函数的调用作为交易的一部分的时候，是需要gas的。例如使用UniswapV2的Router合约swap的时候，会先调用getAmountOut/getAmountIn计算能换多少，然后再调用Pair合约。getAmountOut/getAmountIn是pure函数，但是依然是会消耗gas的。

**Comment by AmazingAng** [comment]
原话 “合约的状态变量存储在链上，gas fee很贵，如果不改写链上变量，就不用付gas。调用pure跟view的函数是不需要付gas的。”
如果不改变脸链上状态，的确不用付gas，swap要给getAmountOut/getAmountIn是因为swap改变了链上状态。
不过单看这一句话的确不够严谨。用户直接调用pure跟view函数，的确是不需要付gas；但如果通过另一个不是pure/view的函数调用，就需要付gas。
我会更新下一句话，让它更严谨。

**Comment by AmazingAng** [comment]
包含`pure`跟`view`关键字的函数是不改写链上状态的，因此用户直接调用他们是不需要付gas的（合约中非`pure`/`view`函数调用它们则会改写链上状态，需要付gas）。

**Comment by CryptoRbtree** [comment]
单一的pure和view的交易是**不必上链**的，但也不是不可以上链，比如看下面这个交易，访问的是pure函数，但是交易上链了，仍然会收gas。非view函数需要收gas是因为这个交易必须上链，否则达不到我们想要的目的；view函数不必上链，因为我们只是想查询。
https://goerli.etherscan.io/tx/0x70d447acfb90eb222cb30251dc0e921c6193f91a19d9a4b4f5668fdda1c8d95d

如果那段话让我来写的话，我会这样表述：
solidity引入pure和view关键字主要是为了控制函数权限和节省gas。对view函数的调用在底层会使用staticcall方法进行函数调用，此时如果修改了链上状态，会导致交易revert，因此pure/view会控制函数的写权限，一定程度上保证了合约安全。如果用户想要调用pure/view函数查询链上状态，是不需要发送上链交易的，因此也不必消耗gas（当然如果你想，调用pure/view函数的交易也是可以上链的，只是没必要）。
