### ISSUE TITLE
第十讲：用solidity实现插入排序，错别字

### ISSUE THREAD

**Issue by qmimi** [AmazingAng/WTF-Solidity#229]
https://github.com/AmazingAng/WTF-Solidity/tree/main/10_InsertionSort
例如[2, 5, 3, 1]，从小到大一次排列好
正确：依次排列，非一次排列

**Comment by AmazingAng** [comment]
感谢 已更新

**Comment by qmimi** [comment]
https://wtf.academy/solidity-start/InsertionSort/
复制了一样的错别字

**Comment by qmimi** [comment]
效率，赞

**Comment by AmazingAng** [comment]
> https://wtf.academy/solidity-start/InsertionSort/ 复制了一样的错别字

这里的也修复了。哈哈
