### ISSUE TITLE
26讲Mirror 总结最后一句话，语病未同步修改（Github上已修改）

### ISSUE THREAD

**Issue by JustinAsdz** [AmazingAng/WTF-Solidity#250]

**Comment by JustinAsdz** [comment]
Mirror：
CREATE2让我们可以在部署合约前确定它的合约地址，**这也反事实系统和很多layer2的基础**。
Github：
CREATE2让我们可以在部署合约前确定它的合约地址，**这也是 一些layer2项目的基础**。

**Comment by XdpCs** [comment]
该问题合并到 #194
