### ISSUE TITLE
批量转账后，转的代币只到了 ERC20 的地址，没有到指定的钱包

### ISSUE THREAD

**Issue by Sylor-huang** [AmazingAng/WTF-Solidity#278]
我是按照这篇文章: [Ethers极简入门: 15. 批量转账](https://wtf.academy/ether-start/MultiTransfer/ ) 来学习的。
- [x] 在goerli 网上完全按照教程部署了 airdrop 合约。

- [x] 发送 eth 交易的代码：

```js
export async function sendTransfer(net_work, formInline) {
  const abiAirdrop = [ 
    "function multiTransferToken(address,address[],uint256[]) external",
    "function multiTransferETH(address[],uint256[]) public payable",
  ];

  let addresses = formInline.to_address.split("\n");
  let toCount = addresses.length
  let amounts = Array(toCount).fill(utils.parseEther(formInline.amount))
// 部署后，ERC20 的地址为 0xDA0bab807633f07f013f94DD0E6A4F96F8742B53
// 合约部署后，合约的地址为 0x9D7f74d0C41E726EC95884E0e97Fa6129e3b5E99
  const addressAirdrop = '0x9D7f74d0C41E726EC95884E0e97Fa6129e3b5E99' // Airdrop Contract
  let provider = await setProvider(net_work)
  console.log(provider)
  console.log(`addresses: ${addresses}\n`)
  console.log(`amounts: ${amounts}\n`)
  let wallet = new ethers.Wallet(formInline.private_key, provider);
  // 声明Airdrop合约
  const contractAirdrop = new ethers.Contract(addressAirdrop, abiAirdrop, wallet)

  // 发起交易
  const tx = await contractAirdrop.multiTransferETH(addresses, amounts)
  // 等待交易上链
  await tx.wait()
  console.log(tx)
  const balanceETH2 = await provider.getBalance(addresses[0])
  console.log(`发送后该钱包ETH持仓: ${ethers.utils.formatEther(balanceETH2)}\n`)
}

```

- [x] 传入的addresses和 amounts 都是正常的

<img width="789" alt="image" src="https://user-images.githubusercontent.com/26167245/196197767-4b953dba-7655-4f57-a59d-ac82264b5f1c.png">

- [x] **但是发送交易后，只是把 eth 发送到了 ERC20 的地址，而不是传入的 addresses 地址**，交易 [hash 链接](https://goerli.etherscan.io/tx/0x5246b1258fbf156f051cb01300f7e3312aad7d6c7b7396fd72cf5864ed6cdffc)

- [ ] 请问这可能是哪个地方的问题呢？非常感谢你们的帮助！

**Comment by Ha2ryZhang** [comment]
`0x9D7f74d0C41E726EC95884E0e97Fa6129e3b5E99`好像不是合约地址

**Comment by Sylor-huang** [comment]
@Ha2ryZhang  请问 remix 发布后，这个应该是合约地址的吧？我使用的是这个地址的

<img width="379" alt="image" src="https://user-images.githubusercontent.com/26167245/196348507-d76ebd34-c51e-4eb6-9893-af87d215cdc9.png">

**Comment by Ha2ryZhang** [comment]
@Sylor-huang 确实是这个地址,看你上面截图的网络默认用的是remix的,而你调用的是goerli测试网的,会不会是这个问题
![image](https://user-images.githubusercontent.com/39999861/196353611-5c53c2e3-eefd-4306-a85e-dd0e1de7dce8.png)

**Comment by Sylor-huang** [comment]
@Ha2ryZhang  应该不是这个问题的，因为我后来用 goerli 测试网络去 deploy 了的。这个发布后的地址是： [0x5F1ff88842a179099F28886aC3eE2a6aE6fef85a](https://goerli.etherscan.io/address/0x5F1ff88842a179099F28886aC3eE2a6aE6fef85a)

但是用这个地址去测试批量转账的话，又会提示 gas 不够， 我用其他的钱包，往这个地址转账 goerli 的测试 eth，也会报错

[转账 hash](https://goerli.etherscan.io/tx/0xf9402e22b30e8085da0112f5995e9f2fc924ef591bbd72d5a7b520049a35e9f8)

<img width="562" alt="image" src="https://user-images.githubusercontent.com/26167245/196356215-e5f96493-97f8-4db1-b647-2101d0267bf1.png">

**Comment by Ha2ryZhang** [comment]
@Sylor-huang 你可以看一下[这里](https://github.com/WTFAcademy/WTF-Ethers/blob/main/15_MultiTransfer/MultiTransfer.js#L79)
`const tx = await contractAirdrop.multiTransferETH(addresses, Array(2).fill(ethers.utils.parseEther("0.001")), { value: ethers.utils.parseEther("0.002") })`和对应的合约一起看一下,看你代码是没有发送value的
我用你部署的合约试了一下是可以的  --[txhash](https://goerli.etherscan.io/tx/0xed92780539cde9279933eb5063d84ed921f8be71fa0ba14ae49ab55b7bcb40fa)

**Comment by Sylor-huang** [comment]
@Ha2ryZhang  确实可以，我这也成功了，代码没抄全。 非常感谢您！！！谢谢~
