### ISSUE TITLE
第24讲: create2创建合约，构造函数可以有参数

### ISSUE THREAD

**Issue by CryptoRbtree** [AmazingAng/WTF-Solidity#280]
第24讲里面说“uniswap使用的是create2创建合约，限制构造函数不能有参数”。
这种说法是错误的，create2并没有这样的限制。例如我把代码改成如下形式，不会有编译或运行上的问题。
只是此时，在计算pair合约地址的时候，需要在creationCode的后面补上tokenA和tokenB。对uniswap来说，这样就会产生一个问题，(tokenA,tokenB)和(tokenB,tokenA)的地址会不一样，uniswap不把tokenA和tokenB放在构造函数里是为了避免token顺序影响合约地址。

`
// SPDX-License-Identifier: GPL-3.0
pragma solidity ^0.8.0;

contract Pair{
    address public factory; // 工厂合约地址
    address public token0; // 代币1
    address public token1; // 代币2

    constructor(address _token0, address _token1) payable {
        factory = msg.sender;
        token0 = _token0;
        token1 = _token1;
    }
}

contract PairFactory2{
        mapping(address => mapping(address => address)) public getPair; // 通过两个代币地址查Pair地址
        address[] public allPairs; // 保存所有Pair地址

        function createPair2(address tokenA, address tokenB) external returns (address pairAddr) {
            require(tokenA != tokenB, 'IDENTICAL_ADDRESSES'); //避免tokenA和tokenB相同产生的冲突
            // 计算用tokenA和tokenB地址计算salt
            (address token0, address token1) = tokenA < tokenB ? (tokenA, tokenB) : (tokenB, tokenA); //将tokenA和tokenB按大小排序
            bytes32 salt = keccak256(abi.encodePacked(token0, token1));
            // 用create2部署新合约
            Pair pair = new Pair{salt: salt}(tokenA, tokenB); 

            // 更新地址map
            pairAddr = address(pair);
            allPairs.push(pairAddr);
            getPair[tokenA][tokenB] = pairAddr;
            getPair[tokenB][tokenA] = pairAddr;
        }

                // 提前计算pair合约地址
        function calculateAddr(address tokenA, address tokenB) public view returns(address predictedAddress){
            require(tokenA != tokenB, 'IDENTICAL_ADDRESSES'); //避免tokenA和tokenB相同产生的冲突
            // 计算用tokenA和tokenB地址计算salt
            (address token0, address token1) = tokenA < tokenB ? (tokenA, tokenB) : (tokenB, tokenA); //将tokenA和tokenB按大小排序
            bytes32 salt = keccak256(abi.encodePacked(token0, token1));
            // 计算合约地址方法 hash()
            predictedAddress = address(uint160(uint(keccak256(abi.encodePacked(
                bytes1(0xff),
                address(this),
                salt,
                abi.encodePacked(keccak256(type(Pair).creationCode),tokenA,tokenB)
            )))));
        }
}
`

**Comment by AmazingAng** [comment]
https://github.com/AmazingAng/WTF-Solidity/pull/273
