### ISSUE TITLE
中文 solidity教程18讲  图片未修改

### ISSUE THREAD

**Issue by JustinAsdz** [AmazingAng/WTF-Solidity#299]
[18讲](https://github.com/AmazingAng/WTF-Solidity/tree/main/18_Import) 图片中有两处问题：
1. 图片中文件名为30（估计是修改顺序之前的序号）
2. 函数结果 为"Yeye hip"，但是对应章节中"Yeye.sol"的import结果应该为"Yeye"

**Comment by JustinAsdz** [comment]
可以考虑直接用我刚刚翻译的英文18讲的[图片](https://github.com/AmazingAng/WTF-Solidity/blob/main/Languages/en/18_Import_en/img/18-1.png)（除代码注释为英文外，上述问题已经被解决）

**Comment by AmazingAng** [comment]
那用英文的吧 你提个pr?
