### ISSUE TITLE
Solidity第49讲 列表名称错误

### ISSUE THREAD

**Issue by DestinyWei** [AmazingAng/WTF-Solidity#302]
实际应为通用可升级代理，但左边列表显示为透明代理

**Comment by AmazingAng** [comment]
UUPS就是通用可升级代理

**Comment by DestinyWei** [comment]
可能我没说清楚 这里的列表是说的WTF官网上的列表噢 不是GitHub上的



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 0xAA ***@***.***&gt;
发送时间: 2022年11月4日 19:56
收件人: AmazingAng/WTF-Solidity ***@***.***&gt;
抄送: DestinyWei ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [AmazingAng/WTF-Solidity] Solidity第49讲 列表名称错误 (Issue #302)

**Comment by DestinyWei** [comment]
详细地址为: https://wtf.academy/solidity-application/UUPS/

**Comment by AmazingAng** [comment]
已修改
