### ISSUE TITLE
Solidity S01。重入攻击中的Remix演示报错

### ISSUE THREAD

**Issue by DestinyWei** [AmazingAng/WTF-Solidity#307]
在执行 [Remix演示](https://wtf.academy/solidity-application/S01_ReentrancyAttack/#remix%E6%BC%94%E7%A4%BA)  的第三步”调用Atack合约的attack()函数发动攻击，调用时需转账1 ETH。“时会 revert "Failed to send Ether"的错误。
经过测试，在本地Hardhat节点测试相同的代码则可以通过，初步判断应该是Remix编译器的处理代码与Hardhat有所差异导致。

**Comment by AmazingAng** [comment]
是的 remix有时报错
