### ISSUE TITLE
第17讲的测试题目里有一题答案有问题

### ISSUE THREAD

**Issue by LIYANG-UST** [AmazingAng/WTF-Solidity#337]
![image](https://user-images.githubusercontent.com/42539774/203716902-f1f12580-88ae-4a09-866f-7b10593f0a2c.png)

**Comment by AmazingAng** [comment]
哪里有问题？

**Comment by LIYANG-UST** [comment]
答案应该是C吧

**Comment by AmazingAng** [comment]
不要讨论答案
