### ISSUE TITLE
第20章的一个测试题有问题

### ISSUE THREAD

**Issue by LIYANG-UST** [AmazingAng/WTF-Solidity#338]
![image](https://user-images.githubusercontent.com/42539774/203720266-d836392e-2412-401d-85b5-f9f04e277c73.png)
正确的方式应该是这样？
``` 
constructor(uint256 _amount) payable {
    payable(address(this)).transfer(_amount);
}
```

**Comment by AmazingAng** [comment]
你写的跟选项有什么不一样

**Comment by LIYANG-UST** [comment]
需要把address(this)转成payable才能使用send和transfer吧

**Comment by AmazingAng** [comment]
> 需要把address(this)转成payable才能使用send和transfer吧

是的 所以这个选项不正确
