### ISSUE TITLE
46讲代理合约的汇编delegatecall函数

### ISSUE THREAD

**Issue by Jiangyj19** [AmazingAng/WTF-Solidity#344]
```
        // delegatecall操作码的参数：gas, 目标合约地址，input mem起始位置，input mem长度，output area mem起始位置，output area mem长度
        // output area起始位置和长度位置，所以设为0
        // delegatecall成功返回1，失败返回0
        let result := delegatecall(gas(), _implementation, 0, calldatasize(), 0, 0)
```
请教下这里output area mem是delegatecall的返回值么，如果是，可以直接把output area mem的长度设置为returndata的长度吗

**Comment by AmazingAng** [comment]
这里使用的是openzeppelin的实现，它是用之后的两行代码来读取返回值的。不知道改了会有什么改变
'''
let size := returndatasize
  returndatacopy(ptr, 0, size)

  switch result
  case 0 { revert(ptr, size) }
  default { return(ptr, size)
'''
相关答案:
https://ethereum.stackexchange.com/questions/89506/how-to-understand-the-last-argument-of-the-solidity-assembly-callg-a-v-in-insiz
