### ISSUE TITLE
19讲和20讲有矛盾的地方

### ISSUE THREAD

**Issue by eartheden** [AmazingAng/WTF-Solidity#347]
19讲这里是这么描述的：
<img width="1090" alt="image" src="https://user-images.githubusercontent.com/107908282/204233401-65f32aff-db7e-470a-adde-625373d3f3da.png">

20讲的代码里面没有fallback 或 reiceve 函数也是可以接受的eth的
<img width="629" alt="image" src="https://user-images.githubusercontent.com/107908282/204233859-ccc886e2-41d7-455b-aab7-f33569ab1e84.png">

**Comment by AmazingAng** [comment]
感谢，在19讲加了对`直接`发送ETH的强调。

`receive()`和`payable fallback()`均不存在的时候，向合约**直接**发送`ETH`将会报错（你仍可以通过带有`payable`的函数向合约发送`ETH`）。
