### ISSUE TITLE
第4讲：BAYC主合约和严重漏洞 [言之过实]

### ISSUE THREAD

**Issue by psyljz** [AmazingAng/WTF-Solidity#354]
个人觉得算不上漏洞，伪去中心化项目，最初就这么设计的。

BUG 1 : 在设计之初就留出了升级的空间，可能是为了防止图片的丢失，可以更换URL。

BUG 2：图片的链接一共只有10000个，他增发了也没图片。

只能说存在私钥被盗了就GG了。

**Comment by AmazingAng** [comment]
只需要增发+更换url 增发的就有图片
