### ISSUE TITLE
《WTF Solidity 合约安全: S11. 抢先交易》脚本有误

### ISSUE THREAD

**Issue by MacroWang001** [AmazingAng/WTF-Solidity#357]
// 2. 创建interface对象，用于解码交易详情。
const iface = new utils.Interface([
    "function mint() external",
])

这段代码VS code 会报错 “ utils未被定义”，应该改为：
const iface = new ethers.utils.Interface([
    "function mint() external",
])

**Comment by AmazingAng** [comment]
第一行已经import utils了，直接用就行
```js
import { ethers, utils } from "ethers";
```
