### ISSUE TITLE
疑问：23讲delegatecall调用函数参数使用uint失败

### ISSUE THREAD

**Issue by lzxeth** [AmazingAng/WTF-Solidity#370]
`(bool success, bytes memory data) = _addr.delegatecall(
            abi.encodeWithSignature("setVars(uint256)", _num)
 );`

请教：setVars函数参数为uint类型，uint也是uint256别名，为什么写为`abi.encodeWithSignature("setVars(uint)", _num)`就调用失败呢？

**Comment by AmazingAng** [comment]
规则 这里必须写为uint256
