### ISSUE TITLE
请问关于这里的license

### ISSUE THREAD

**Issue by thurendous** [AmazingAng/WTF-Solidity#373]
https://github.com/AmazingAng/WTF-Solidity/blob/4178a8c3f188a4a2fd5413bc7f20df5af6ca6be4/45_Timelock/Timelock.sol#L1
这里的license的话，应该是不能商业利用的哈？

**Comment by AmazingAng** [comment]
你好，在咨询专业法律人士并参考MDN教程的license后，我们更新了WTF Solidity的license。[链接](https://github.com/AmazingAng/WTF-Solidity/blob/main/LICENSE)

简单来说，代码部分遵从MIT许可，文字部分遵从CC BY-NC-SA 4.0许可（署名-非商业性运用-相同方式共享）。
