### ISSUE TITLE
第16节 重载 实参匹配，并未出现预期的效果

### ISSUE THREAD

**Issue by lurengeng** [AmazingAng/WTF-Solidity#378]
// 教程里说，由于实参匹配，50既可以被转换为uint8,也可以被转换为uint256,因此报错。实际测试并没有报错
    function f(uint8 _in) public pure returns (uint8 out) {
        out = _in;
    }

    function f(uint256 _in) public pure returns (uint256 out) {
        out = _in;
    }

![image](https://user-images.githubusercontent.com/61215384/210814405-981ba5e0-e7c7-4cf3-9a43-0489d754bfe3.png)

**Comment by AmazingAng** [comment]
remix里不会报这个错，因为你调用的时候已经确定了哪个函数，它帮你做了类型转换
