### ISSUE TITLE
29_Selector address 好像不应该加双引号

### ISSUE THREAD

**Issue by rpnanhai** [AmazingAng/WTF-Solidity#385]
`(bool success, bytes memory data) = address(this).call(abi.encodeWithSelector(0x6a627842, "0x2c44b726ADF1963cA47Af88B284C06f30380fC78"));`

<img width="917" alt="image" src="https://user-images.githubusercontent.com/6694945/211509280-c6b6d41c-4432-4463-8042-9d3aa46519fa.png">

**Comment by AmazingAng** [comment]
你是对的，感谢建议，已更正。
