### ISSUE TITLE
「删除合约」章节建议增加「不建议使用」的声明

### ISSUE THREAD

**Issue by jeasonstudio** [AmazingAng/WTF-Solidity#407]
在 [2023/02/01 release 的 solidiy 0.8.18 版本编译器](https://blog.soliditylang.org/2023/02/01/solidity-0.8.18-release-announcement/)中，已经增加了对于 `selfdestruct` 的弃用警告，原因可参考 [EIP-6049](https://eips.ethereum.org/EIPS/eip-6049);
建议在对应章节也增加与之相关的描述；

**Comment by AmazingAng** [comment]
好建议，你可以写个pr把这个加进去吗？
