### ISSUE TITLE
solidity入门 最后两讲的测试 不管怎么选准确率都是 85%

### ISSUE THREAD

**Issue by ClearLovePlus** [AmazingAng/WTF-Solidity#413]
<img width="665" alt="image" src="https://user-images.githubusercontent.com/33109146/217542265-fd20c6c9-300f-4a83-bad8-743c64217f75.png">
<img width="768" alt="image" src="https://user-images.githubusercontent.com/33109146/217542336-64d65a78-21eb-4843-9771-2ad8f27a717e.png">
<img width="630" alt="image" src="https://user-images.githubusercontent.com/33109146/217542676-bf883285-5733-4d8c-ad3e-50f1226f2dda.png">
<img width="666" alt="image" src="https://user-images.githubusercontent.com/33109146/217542719-366fa891-5158-4173-9c53-a9a121d3e77a.png">
很奇怪，怎么选都是85%。。

**Comment by AmazingAng** [comment]
https://github.com/AmazingAng/WTF-Solidity/discussions/260
