### ISSUE TITLE
19. 接收ETH receive和fallback

### ISSUE THREAD

**Issue by Johnny0song** [AmazingAng/WTF-Solidity#417]
部署的时候往合约里面转eth会报错, 加上 constructor() payable {} 就可以了

// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

contract Fallback {
    constructor() payable {}
    /* 触发fallback() 还是 receive()?
           接收ETH
              |
         msg.data是空？
            /  \
          是    否
          /      \
receive()存在?   fallback()
        / \
       是  否
      /     \
receive()  fallback   
    */

    // 定义事件
    event receivedCalled(address Sender, uint Value);
    event fallbackCalled(address Sender, uint Value, bytes Data);

    // 接收ETH时释放Received事件
    receive() external payable {
        emit receivedCalled(msg.sender, msg.value);
    }

    // fallback
    fallback() external payable{
        emit fallbackCalled(msg.sender, msg.value, msg.data);
    }
}

**Comment by AmazingAng** [comment]
是的 要想在部署时往合约里转eth，consturctor要 payable
