### ISSUE TITLE
第39講 鏈上隨機數生成readme的示範code與描述內容有誤

### ISSUE THREAD

**Issue by RoyHonChain** [AmazingAng/WTF-Solidity#420]
"下面的getRandomOnchain()函数利用全局变量block.number，msg.sender和blockhash(block.timestamp-1)作为种子来获取随机数："
這行應改為->"下面的getRandomOnchain()函数利用全局变量block.timestamp，msg.sender和blockhash(block.number-1)作为种子来获取随机数："

```
    /** 
    * 链上伪随机数生成
    * 利用keccak256()打包一些链上的全局变量/自定义变量
    * 返回时转换成uint256类型
    */
    function getRandomOnchain() public view returns(uint256){
        // remix运行blockhash会报错
        bytes32 randomBytes = keccak256(abi.encodePacked(block.number, msg.sender, blockhash(block.timestamp-1)));
        
        return uint256(randomBytes);
    }
```

bytes32 randomBytes = keccak256(abi.encodePacked(block.number, msg.sender, blockhash(block.timestamp-1)));
這行應改為->bytes32 randomBytes = keccak256(abi.encodePacked(block.timestamp, msg.sender, blockhash(block.number-1)));

**Comment by AmazingAng** [comment]
为什么不能用timestamp?

**Comment by RoyHonChain** [comment]
我在hardhat測試過不了，上網查文件blockhash裡面要放的是blocknumber，會回傳該block的hash。
這樣我的程式碼可以正確運行。

**Comment by RoyHonChain** [comment]
![image](https://user-images.githubusercontent.com/106396981/220409671-948a52a1-1c63-4814-885b-143c660d5501.png)
https://docs.soliditylang.org/en/v0.4.24/units-and-global-variables.html

**Comment by AmazingAng** [comment]
的确，你是对的。
你要不要提个pr修改下？

**Comment by RoyHonChain** [comment]
sure~
