### ISSUE TITLE
关于46讲的描述的偏差

### ISSUE THREAD

**Issue by wishucry** [AmazingAng/WTF-Solidity#427]
文中描述“
代理模式主要有两个好处：
可升级：当我们需要升级合约的逻辑时，只需要将代理合约指向新的逻辑合约。
省gas：如果多个合约复用一套逻辑，我们只需部署一个逻辑合约，然后再部署多个只保存数据的代理合约，指向逻辑合约。
”
其中第二点省Gas建议改成，节省部署合约的Gas费用。因为代理合约在每次被调用时的Gas要比普通合约要高，总体来说频繁调用的情况下更加消耗Gas，只是省了多次部署的费用。

**Comment by AmazingAng** [comment]
每次调用高多少呢?

**Comment by wishucry** [comment]
每次调用时会先访问代理合约里存储的逻辑合约地址插槽，首先这里会有一个固定开销，这个值至少上百Gas。

**Comment by AmazingAng** [comment]
好 你提个pr把缺点加进去吧
