### ISSUE TITLE
S16：NFT重入攻击 报错：ERC721: transfer to non ERC721Receiver implementer

### ISSUE THREAD

**Issue by lzxeth** [AmazingAng/WTF-Solidity#429]
**问题描述：**
使用【S16：NFT重入攻击】 内代码部署后，执行报错
`
transact to Attack.attack errored: VM error: revert.

revert
	The transaction has been reverted to the initial state.
Reason provided by the contract: "ERC721: transfer to non ERC721Receiver implementer".
`

**执行环境：**
chrome浏览器remix, Remix VM(London)

尝试修改_onERC721Received_函数内mint NFT的个数，多次尝试，只有小于10才能成功，大于10都会报如上错误
所以，攻击合约明明已经实现了onERC721Received函数，但是mint次数超过10就报错未实现，不知道是什么原因导致，请大神指点

**Comment by tgblackhat** [comment]
I have the same issue

**Comment by AmazingAng** [comment]
可能是Remix 本地EVM的问题，已经改成10个。

**Comment by tgblackhat** [comment]
This is not a solution to the problem. If you deploy to the Goerli network, the problem persists.

**Comment by tgblackhat** [comment]
> 可能是Remix 本地EVM的问题，已经改成10个。

This is not a solution to the problem. If you deploy to the Goerli network, the problem persists.

**Comment by zhiyuan2007** [comment]
> 可能是Remix 本地EVM的问题，已经改成10个。

应该是AA说的这个原因， 因为我在本地remix也出现这个问题，但是在goerli测试网上就没有复现，攻击多少个都没问题，攻击越多需要的gas越多，这个是例子，里边重入攻击数量是50 ，https://goerli.etherscan.io/tx/0xda55bf7cb66e57df2f61a30e1c29573b9b3db7b57ebf61c6bacacfee949632a6

**Comment by zhiyuan2007** [comment]
> > 可能是Remix 本地EVM的问题，已经改成10个。
> 
> This is not a solution to the problem. If you deploy to the Goerli network, the problem persists.

I verified this on the goerli test network and there is no problem, so it is a local evm problem,  refer to the above url

**Comment by tgblackhat** [comment]
> > > 可能是Remix 本地EVM的问题，已经改成10个。
> > 
> > 
> > This is not a solution to the problem. If you deploy to the Goerli network, the problem persists.
> 
> I verified this on the goerli test network and there is no problem, so it is a local evm problem, refer to the above url

Could you verify both contracts (NFT and Reentrancy)?
