### ISSUE TITLE
第16讲：函数重载，最后一题都可以转为50，不会报错

### ISSUE THREAD

**Issue by dongyuanwai** [AmazingAng/WTF-Solidity#431]
![image](https://user-images.githubusercontent.com/83452331/222955055-e4c4e8ba-3369-43da-b986-d767dd24cf59.png)

**Comment by AmazingAng** [comment]
是的，在remix里不会报错，因为它帮你处理了类型转换。但如果你在脚本里直接调用，可能会报错。
