### ISSUE TITLE
S08：绕过合约检查 預防辦法部分可能有漏洞

### ISSUE THREAD

**Issue by RoyHonChain** [AmazingAng/WTF-Solidity#432]
以下這一段內容 是不是可能有漏洞
`你可以使用 (tx.origin == msg.sender) 来检测调用者是否为合约。如果调用者为 EOA，那么tx.origin和msg.sender相等；如果它们俩不相等，调用者为合约。`

假設背景設定為：
- EOA、合約A(惡意合約)、合約B(檢查是否為合約)
- 合約A裡面有個函數是delegatecall另外一個合約

操作為：
1. 我用EOA -call-> 合約A
2. 合約A -delegatecall->合約B

那我在合約B看到的 tx.origin 與 msg.sender 都為我的 EOA
這樣是否就繞開合約檢查了呢？

![image](https://user-images.githubusercontent.com/106396981/223478418-b5e61573-db94-41c1-aaba-8fee40406cc3.png)

當然這麼做可能意義不大，因為語境在合約A，合約B的資料理應不受影響。
但還是可以繞開檢查

**Comment by AmazingAng** [comment]
Delegatecall合约B不会改变B的状态，而是改变A（恶意合约）。
你再看看delegatecall章节
