### ISSUE TITLE
第33讲：空投示例得不到期望结果

### ISSUE THREAD

**Issue by GrayJyy** [AmazingAng/WTF-Solidity#433]
按照教程发送100，200空投后，查询第一个地址的余额是100，但是第二个地址的余额变成了9900
<img width="1229" alt="image" src="https://user-images.githubusercontent.com/122503129/223671518-81544395-a6d8-4785-acd0-fab3bbb57c01.png">

**Comment by sugarforever** [comment]
@GrayJyy 确实如此。原因在于0x5B38Da6a701c568545dCfcB03FcB875f56beddC4默认是Remix里的第一个账号，所以部署合约的时候如果不做修改，都是用的它。铸造操作默认也是用的这个账号，因此它的余额在铸造后就是10000。
课程中空投的目标账号["0xAb8483F64d9C6d1EcF9b849Ae677dD3315835cb2", "0x5B38Da6a701c568545dCfcB03FcB875f56beddC4"]正好包含了部署账号。也就是说自己给自己空投了。

如果你把空投目标账号换成两个其他账号，再操作一下，应该就明白怎么回事了。
