### ISSUE TITLE
操纵预言机：Oracle.sol中import的IERC20.sol路径变了

### ISSUE THREAD

**Issue by hsgui** [AmazingAng/WTF-Solidity#458]
最新的路径应该是：
import "openzeppelin-contracts/contracts/token/ERC20/IERC20.sol";
import "openzeppelin-contracts/contracts/token/ERC20/ERC20.sol";

多了一个子目录："contracts"

**Comment by AmazingAng** [comment]
最新的foundry么

**Comment by hsgui** [comment]
是的

**Comment by XdpCs** [comment]
目录没有变更
<img width="667" alt="image" src="https://github.com/user-attachments/assets/781e808b-69e9-4a61-be00-3ba8e2165860">
