### ISSUE TITLE
中文 mapping 类型错误

### ISSUE THREAD

**Issue by waha3** [AmazingAng/WTF-Solidity#460]
`// 我们定义一个结构体 Struct
    struct Student{
        uint256 id;
        uint256 score; 
    }
 mapping(Student => uint) public testVar;`
Student 类型写错了

**Comment by AmazingAng** [comment]
没有错啊

**Comment by waha3** [comment]
0.8.x的编译器提示报错 struct 不能作为map的key

**Comment by AmazingAng** [comment]
原文
> 规则1：映射的_KeyType只能选择solidity默认的类型，比如uint，address等，不能用自定义的结构体。而_ValueType可以使用自定义的类型。下面这个例子会报错，因为_KeyType使用了我们自定义的结构体：
