### ISSUE TITLE
第39讲 chainlink预言机 Random.sol

### ISSUE THREAD

**Issue by cjh20000613** [AmazingAng/WTF-Solidity#469]
使用Goerli网络，参数从https://docs.chain.link/vrf/v1/supported-networks找到
但合约部署，不管转没转LINK，调用getRandomNumber函数时都报错

![IGX}16}1YE_ @FQ28D7JZVW](https://user-images.githubusercontent.com/65795263/230256306-8220370b-6304-40ef-ade5-8a7a254c5ace.png)

**Comment by yoharsh14** [comment]
Can you guide me which contract is it in the repository
