### ISSUE TITLE
revert undeclared identifier

### ISSUE THREAD

**Issue by xinming365** [AmazingAng/WTF-Solidity#470]
Why would this error appear when using call method? Is the version of solidity not corrected?

DeclarationError: Undeclared identifier.
  --> contracts/test.sol:70:20:
   |
70 |             revert CallFailed();
   |                    ^^^^^^^^^^

**Comment by Azleal** [comment]
确认下是否有`error CallFailed();`的定义

**Comment by yoharsh14** [comment]
Add `error CallFailed();` above outside the contract
