### ISSUE TITLE
项目Readme中的捐赠-Mirror 链接  Page not found.

### ISSUE THREAD

**Issue by yanboishere** [AmazingAng/WTF-Solidity#484]
该链接 点击后显示为 Page not found. ：https://mirror.xyz/ninjak.eth/collection

**Comment by yanboishere** [comment]
<img width="1198" alt="截屏2023-04-21 上午9 22 13" src="https://user-images.githubusercontent.com/76860915/233518706-8cb752ff-5295-4b44-ab68-0c054484b31d.png">

**Comment by yanboishere** [comment]
<img width="816" alt="截屏2023-04-21 上午9 22 13" src="https://user-images.githubusercontent.com/76860915/233518857-6d4a91da-de91-4514-a90d-55262ce90d2b.png">

**Comment by AmazingAng** [comment]
已修改
