### ISSUE TITLE
ERC20Permit拿DAI举例不对

### ISSUE THREAD

**Issue by lxhyl** [AmazingAng/WTF-Solidity#505]
https://github.com/AmazingAng/WTF-Solidity/blob/main/53_ERC20Permit/readme.md

上面的文章拿DAI举例有误, 实际上DAI的permit并不是ERC20Permit标准实现.先有的DAI，再有的ERC20Permit标准。

* DAI的部署日期可以在etherscan看到(https://etherscan.io/tx/0x495402df7d45fe36329b0bd94487f49baee62026d50f654600f6771bd2a596ab)是： Nov-13-2019 07:17:57 PM +UTC.       
* 而ERC20Permit标准提出已经是（https://eips.ethereum.org/EIPS/eip-2612）:  2020-04-13了.   
*  签名的前端代码DAI也和标准ERC20Permit有所不同，参见uniswap的前端代码：https://github.com/Uniswap/interface/blob/main/src/hooks/useERC20Permit.ts

**Comment by AmazingAng** [comment]
的确，可以提个pr修改下吗？

**Comment by lxhyl** [comment]
DAI改成USDC了.  https://github.com/AmazingAng/WTF-Solidity/pull/506
