### ISSUE TITLE
struct 类型的函数参数

### ISSUE THREAD

**Issue by jackie-rachel** [AmazingAng/WTF-Solidity#528]
struct类型的函数参数如何传参

**Comment by shenyushun** [comment]
中括号包起来，按定义顺序逗号分割。

比如
["0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174","0xc2132D05D31c914a87C6611C10748AEb04B58e8F","0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174",500,10]
