### ISSUE TITLE
实在没找出23题哪里做错了

### ISSUE THREAD

**Issue by edxzh** [AmazingAng/WTF-Solidity#531]
一直是83分，但是我怎么都感觉这6道题都是对的，希望哪位能指出问题：
我的答案：
1.delegatecall是哪个类型的成员函数： address
2. 当用户A通过合约B来delegatecall合约C时，执行了__的函数，语境是__，msg.sender和msg.value来自__， 并且如果函数改变一些状态变量，产生的效果会作用于__的变量上: C;B;A;B
3. delegatecall在调用合约时: 可以指定交易发送的gas，但不可以指定发送的ETH数额
4. 使用delegatecall对当前合约和目标合约的状态变量有什么要求？: 变量名、变量类型、声明顺序都必须相同
5. 假设存在如下函数：那么下面选项中可以填在横线上的是？ (bool success, bytes memory data) = _addr.delegatecall(abi.encodeWithSignature("mint(uint256)", _num));
6. 在代理合约中，存储所有相关的变量的是___，存储所有函数的是___，同时____________ : 代理合约; 逻辑合约; 代理合约delegatecall逻辑合约

**Comment by TanLingxiao** [comment]
4, 5 错了 建议查一下资料或者用remix跑一下

**Comment by XdpCs** [comment]
4和5 存在问题
4. 使用delegatecall对当前合约和目标合约的状态变量有什么要求？: 
     变量类型、声明顺序都必须相同，变量名可以不同，因为其实就是一个个slot的对应
![image](https://github.com/AmazingAng/WTF-Solidity/assets/72180730/d8f7c339-4031-44ac-a312-f49f10eb5e94)

6. 假设存在如下函数：那么下面选项中可以填在横线上的是？ 
     (bool success, bytes memory data) = addr.delegatecall(abi.encodeWithSignature("mint(uint256)", _num));
     注意一下，num并没有声明过，传入的变量名字叫_num

**Comment by XdpCs** [comment]
@AmazingAng 有空可以关闭一下issue
