### ISSUE TITLE
第19题的,vitalik想部署一个能接收ETH和msg.data的合约，那么他部署的合约中必须含有fallback函数

### ISSUE THREAD

**Issue by w402116500** [AmazingAng/WTF-Solidity#556]
![image](https://github.com/AmazingAng/WTF-Solidity/assets/146823641/9bf440f3-9893-4544-818e-0a45d4511aab)
这题我一直感觉有问题,不是单一个receive函数就可以了吗?为什么非要有fallback函数

**Comment by AmazingAng** [comment]
receive函数不能接受msg.data

**Comment by XdpCs** [comment]
@AmazingAng 有空可以关闭一下issue
