### ISSUE TITLE
26讲selfdestruct使用后读取合约状态变量问题

### ISSUE THREAD

**Issue by epitaphial** [AmazingAng/WTF-Solidity#557]
<img width="1271" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/35803206/0b788a16-ace4-456f-9a59-c8fe8bdfd9d6">
solidity编译器版本：pragma solidity ^0.8.4;
可以看到这个环境下，selfdestruct调用后读取状态变量不为0，而是返回错误代码

**Comment by AmazingAng** [comment]
对，新版本的remix改了。
你提个pr更新下教程？

**Comment by epitaphial** [comment]
> 对，新版本的remix改了。 你提个pr更新下教程？

好的~

**Comment by XdpCs** [comment]
@AmazingAng 有空可以关闭一下issue
