### ISSUE TITLE
34讲的Address库是不是没有这个函数

### ISSUE THREAD

**Issue by cole123466** [AmazingAng/WTF-Solidity#558]
![1](https://github.com/AmazingAng/WTF-Solidity/assets/75599847/aa3e3c63-20e7-441b-b4ce-f3aac57c2a8d)

**Comment by AmazingAng** [comment]
应该是openzeppelin最新版把这个函数删除了 需要更新一下教程
有空提个pr不？

**Comment by cxp-13** [comment]
> 教

不是，他应该导入你教程的Address.sol,而不是openzepplin的
