### ISSUE TITLE
ethers-102/MultiTransfer/ 批量转账金额错了

### ISSUE THREAD

**Issue by skywalker2017** [AmazingAng/WTF-Solidity#589]
<img width="1357" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/19268240/1f400555-90ca-4113-8f7b-7520c9555763">

**Comment by XdpCs** [comment]
Fix in this commit.
https://github.com/WTFAcademy/WTF-Ethers/commit/0247cf548362effe604b57d2febc756d74eb1b31
