### ISSUE TITLE
52讲-EIP712，其中的html文件运行报错

### ISSUE THREAD

**Issue by cxp-13** [AmazingAng/WTF-Solidity#602]
![image](https://github.com/AmazingAng/WTF-Solidity/assets/84974164/1cbe71ff-9abc-40c3-8cab-deba4e26601c)
已经讲合约地址改为部署的地址

**Comment by gsangeryee** [comment]
这是因为 MetaMask 的内容安全策略（Content Security Policy）的要求。MetaMask 只会在通过 HTTP/HTTPS 协议访问的页面中注入 window.ethereum 对象，而不会在直接打开的本地文件（file:// 协议）中注入。

所以需要在本地服务器中加载 html 文件才可以运行。我使用的是 VS code 的  Live Server 插件。

**Comment by XdpCs** [comment]
增加这个点的解释，可以让大家更好的使用教程
