### ISSUE TITLE
38节的nftswap这点始终报错，这个本案例中为WTFApe合约地址是那个地址，求大佬给个截图，快疯了

### ISSUE THREAD

**Issue by kongjining** [AmazingAng/WTF-Solidity#605]
38节的nftswap这点始终报错，这个本案例中为WTFApe合约地址是那个地址，求大佬给个截图，快疯了
4. 上架NFT
调用NFTSwap合约的list()函数，将自己持有的tokenId为0的NFT上架到NFTSwap，价格设为1 wei。

list(address _nftAddr, uint256 _tokenId, uint256 _price)方法有3个参数:

_nftAddr: _nftAddr为NFT合约地址，本案例中为WTFApe合约地址。

_tokenId: _tokenId为NFT的id，本案例中为上述mint的0Id。

_price: _price为NFT的价格，本案例中为1 wei。

按照上述方法，同理将自己持有的tokenId为1的NFT上架到NFTSwap，价格设为1 wei。

**Comment by AmazingAng** [comment]
就是你创建的erc721合约地址。
