### ISSUE TITLE
Solidity 19 接受 ETH，试题 4 和 5

### ISSUE THREAD

**Issue by Abysssea** [AmazingAng/WTF-Solidity#611]
我试了一下，试题 4 和 5 都是提示没有 fallback 函数，也就是运行时错误，但是原文：

```
触发fallback() 还是 receive()?
           接收ETH
              |
         msg.data是空？
            /  \
          是    否
          /      \
receive()存在?   fallback()
        / \
       是  否
      /     \
receive()   fallback()
```

> 简单来说，合约接收ETH时，msg.data为空且存在receive()时，会触发receive()；msg.data不为空或不存在receive()时，会触发fallback()，此时fallback()必须为payable。

> receive()和payable fallback()均不存在的时候，向合约直接发送ETH将会报错（你仍可以通过带有payable的函数向合约发送ETH）。

按照我对原文的理解，如果没有 fallback 函数，那最终会调用 receive 函数，而不是报错，所以教程是否有问题，还是我哪里理解错了？

**Comment by AmazingAng** [comment]
没有fallback函数，但是交易中发了data，会报错
