### ISSUE TITLE
quizes are in chinese despite using english

### ISSUE THREAD

**Issue by ajaxbo360** [AmazingAng/WTF-Solidity#613]
<img width="1115" alt="Screen Shot 2023-12-29 at 00 32 31" src="https://github.com/AmazingAng/WTF-Solidity/assets/57604163/eb932a4a-34b7-4ab4-b452-f2151852ad52">
i get the error as you see in this screenshot when switching to english

**Comment by ajaxbo360** [comment]
i think there is some error in language internationalize (i18n)

**Comment by AmazingAng** [comment]
Thx for reporting this bug! We will fix it asap

**Comment by ajaxbo360** [comment]
i can investigate about the issue and see if theres a fix

**Comment by AmazingAng** [comment]
Thx

**Comment by AmazingAng** [comment]
its in this repo: https://github.com/WTFAcademy/frontend
