### ISSUE TITLE
第二章值类型里面对短路规则描述有错误

### ISSUE THREAD

**Issue by gunksd** [AmazingAng/WTF-Solidity#646]
“当逻辑或（&&）的第一个条件为假时，就不会再去判断第二个条件；当逻辑与（||）的第一个条件为真时，就不会再去判断第二个条件，这就是短路规则。”
[这一段表述是不是有错误？]

![04f163b036e48a60343ab340a9535565](https://github.com/AmazingAng/WTF-Solidity/assets/114794418/5112166f-f621-4be2-a6d3-297ebd737f10)

**Comment by XdpCs** [comment]
逻辑或和逻辑与的符号写反了

**Comment by fuchanghai** [comment]
@XdpCs @0x4E33 plz close this issue
