### ISSUE TITLE
第十三章关于modifier继承的代码顺序需要调整

### ISSUE THREAD

**Issue by CaoHongchang** [AmazingAng/WTF-Solidity#650]
您好~
modifier exactDividedBy2And3(uint _a) override {
    _;
    require(_a % 2 == 0 && _a % 3 == 0);
}
这样 _; 占位符是不是要在 require 下面
modifier onlyOwner {
   require(msg.sender == owner); // 检查调用者是否为owner地址
   _; 
}

**Comment by XdpCs** [comment]
是的

**Comment by CaoHongchang** [comment]
感谢回复, 祝WTF-Solidity项目星星越来越多


睡在浴缸里的人
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AmazingAng/WTF-Solidity"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年3月8日(星期五) 下午3:07
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [AmazingAng/WTF-Solidity] 第十三章关于modifier继承的代码顺序需要调整 (Issue #650)





 
是的
