### ISSUE TITLE
pictures can't display in English version

### ISSUE THREAD

**Issue by MurphyYue** [AmazingAng/WTF-Solidity#665]
The pictures  in the chapters from 16 to 50 in English version can't display normally.
Perhaps the assets can't found, please check the webpack config or bundle rules.

![pics](https://github.com/AmazingAng/WTF-Solidity/assets/20450082/427e02f8-56a5-48a7-a93a-c0a9d6dee2f6)

**Comment by nipudas29** [comment]
hey @MurphyYue , i would love to contribute to this issue, could you please assign it to me

**Comment by XdpCs** [comment]
fix this issue in the https://github.com/WTFAcademy/frontend
