### ISSUE TITLE
[feature] 添加issue 模版

### ISSUE THREAD

**Issue by fuchanghai** [AmazingAng/WTF-Solidity#668]
我觉得我们更需要issue 的模版，因为贡献者和committer 更希望知道出现了什么问题，哪个分支上有问题，以及提issue 的人是否愿意解决（当用户没有意愿解决时，有意愿的潜在贡献者可以申请来解决，否则issue 会一直挂在那里），以下是apache 某个项目的issue 模版
<img width="936" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/33984497/c0c72a66-6797-4374-9cfa-f891092e52a2">
<img width="1340" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/33984497/32f18354-7169-47c9-84a8-3511f3b84e70">

cc @AmazingAng  @XdpCs

**Comment by XdpCs** [comment]
这个issue模版 我还在调研😂 有很多种分类

**Comment by fuchanghai** [comment]
> 这个issue模版 我还在调研😂 有很多种分类

hi @XdpCs  遵守协议的选项也很重要，省的以后会出现掰头协议问题 cc @AmazingAng

**Comment by fuchanghai** [comment]
> 这个issue模版 我还在调研😂 有很多种分类

找个项目copy 一下就好 哈哈

**Comment by XdpCs** [comment]
> > 这个issue模版 我还在调研😂 有很多种分类
> 
> hi @XdpCs 遵守协议的选项也很重要，省的以后会出现掰头协议问题 cc @AmazingAng

这个似乎有类似的机器人好像 因为我当时贡献Microsoft仓库 他们就有类似的设计

**Comment by fuchanghai** [comment]
> > > 这个issue模版 我还在调研😂 有很多种分类
> > 
> > 
> > hi @XdpCs 遵守协议的选项也很重要，省的以后会出现掰头协议问题 cc @AmazingAng
> 
> 这个似乎有类似的机器人好像 因为我当时贡献Microsoft仓库 他们就有类似的设计

加一个协议规则的链接就行，默认不选中。用户必须点遵守规则才能提交。我看作者的推特上说知乎就有个人拷贝的他的文章～～

**Comment by XdpCs** [comment]
@fuchanghai 记得关闭一下issue
