### ISSUE TITLE
[TODO] 11讲演示示例更新

### ISSUE THREAD

**Issue by AmazingAng** [AmazingAng/WTF-Solidity#674]
合约更新到Solidity 0.8.21，并参考了openzeppelin最新版。
示例截图需要更新: https://github.com/AmazingAng/WTF-Solidity/tree/main/11_Modifier

**Comment by XdpCs** [comment]
@AmazingAng  能否给一些已经修改成openzeppelin最新版 的 课程

**Comment by XdpCs** [comment]
@AmazingAng 有空可以关闭一下issue
