### ISSUE TITLE
在第23讲：Delegatecall中uint256和uint问题

### ISSUE THREAD

**Issue by zxcvbn001** [AmazingAng/WTF-Solidity#677]
在第23讲：Delegatecall中，setVars函数的参数我写的是uint
![image](https://github.com/AmazingAng/WTF-Solidity/assets/23741141/fb791d0e-3518-4f88-af52-420e4607b797)
B调用C的setVars就无法成功，改成uint256就行 这是为何

**Comment by AmazingAng** [comment]
![Screenshot_2024-03-18-02-24-49-589_com.github.android.jpg](https://github.com/AmazingAng/WTF-Solidity/assets/14728591/c12f4189-2e8f-4fd1-b2ee-d947e177c8d1)
