### ISSUE TITLE
大佬请教个重入问题

### ISSUE THREAD

**Issue by zxcvbn001** [AmazingAng/WTF-Solidity#678]
在这个https://github.com/AmazingAng/WTF-Solidity/blob/main/S01_ReentrancyAttack/ReentrancyAttack.sol
合约重入的例子里面，我测试发现初始存入15以内的eth，可以完成攻击，初始存入20个就会攻击失败，请问是什么原因呢
![image](https://github.com/AmazingAng/WTF-Solidity/assets/23741141/08920b76-9fda-4832-9337-ec6fc34e865c)

**Comment by zxcvbn001** [comment]
A账户存入15 ，B可以攻击成功；A存入20，B攻击不成功

**Comment by AmazingAng** [comment]
Remix vm的bug，你换其他链就能攻击成功
