### ISSUE TITLE
[Feature]  自动同步上游仓库

### ISSUE THREAD

**Issue by XdpCs** [AmazingAng/WTF-Solidity#695]
**🧐 Motivation(动机)**

WTF-Academy fork的仓库 时常同步不及时

**📝 Details(细节)**

ref: https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web/blob/main/.github/workflows/sync.yml

I will fix it.

**Comment by XdpCs** [comment]
仅支持了 学院的fork 仓库
如果后面有用户 需要支持 后面再加

**Comment by AmazingAng** [comment]
辛苦了
