### ISSUE TITLE
S14中导入openzeppelin中的ERC721.sol代码错误

### ISSUE THREAD

**Issue by muzikoud** [AmazingAng/WTF-Solidity#698]
![微信图片_20240330173439](https://github.com/AmazingAng/WTF-Solidity/assets/74277262/07a2b471-7e61-45b3-97fb-558379e3a24a)

应修改为import "@openzeppelin/contracts/token/ERC721/ERC721.sol";

**Comment by XdpCs** [comment]
I will fix it.

**Comment by XdpCs** [comment]
<img width="658" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/72180730/8d13e538-7d50-4031-91fe-2c053479684e">

确认确实有这个问题

**Comment by XdpCs** [comment]
你好 这个教程使用的是Foundry的框架
可能你用的是remix 可能导入存在差异
我使用Foundry框架运行 未出现你所说的导入问题
<img width="390" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/72180730/a99e0554-6312-4b4e-9dc3-b06f5dd7c201">

**Comment by XdpCs** [comment]
<img width="567" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/72180730/c200bf87-7758-49c0-acdb-72927a41d9c1">

**Comment by XdpCs** [comment]
https://github.com/AmazingAng/WTF-Solidity/blob/main/Topics/Tools/TOOL07_Foundry/readme.md 
https://book.getfoundry.sh/forge/cheatcodes
相关教程

**Comment by XdpCs** [comment]
@AmazingAng 有空可以关闭一下issue
