### ISSUE TITLE
Language initialization issue in quiz

### ISSUE THREAD

**Issue by Hack3rM3N** [AmazingAng/WTF-Solidity#701]
<img width="1386" alt="Screenshot 2024-04-05 at 13 36 51" src="https://github.com/AmazingAng/WTF-Solidity/assets/70050021/8c7d8345-970e-4c22-9c9a-70385b15a6cd">
Whenever I switch to english in quiz it encounters an error.

**Comment by XdpCs** [comment]
can you submit this issue to the https://github.com/WTFAcademy/frontend
