### ISSUE TITLE
Goeril -> Sepolia

### ISSUE THREAD

**Issue by OS-Lihua** [AmazingAng/WTF-Solidity#702]
**🧐 Motivation(动机)**

我没有Goeril，无法领取网站的NFT证书，Goeril将被弃用
**📝 Details(细节)**

我希望网站证书能改成 Sepolia 的NFT

**Comment by rictt** [comment]
+1

**Comment by KelvinTsui820** [comment]
+1

**Comment by jireve999** [comment]
+1

**Comment by wzl521** [comment]
+1，不能申领证书啦

**Comment by Yazzyk** [comment]
+1

**Comment by denghaosS2024** [comment]
+1

**Comment by arnold-zhang-jlu** [comment]
+1

**Comment by AmazingAng** [comment]
很快会部署到base 大家期待一下

**Comment by yanboishere** [comment]
> 很快会部署到base 大家期待一下

赞

**Comment by XdpCs** [comment]
已经部署到base
@OS-Lihua 该issue有空可以关闭一下 谢谢

**Comment by wzl521** [comment]
这个证书还需要eth吗？

**Comment by AmazingAng** [comment]
> 这个证书还需要eth吗？

是的，见 https://github.com/AmazingAng/WTF-Solidity/discussions/739

目前铸造最少需要捐 0.0069 ETH。

**Comment by wzl521** [comment]
好吧，那还是领取不了

**Comment by AmazingAng** [comment]
> 好吧，那还是领取不了

成为wtf academy的贡献者可以免费领取
