### ISSUE TITLE
这个人发布内容跟你的一模一样

### ISSUE THREAD

**Issue by caihuach** [AmazingAng/WTF-Solidity#708]
[Solidity极简入门#13. 继承](https://blog.51cto.com/sleep666/6051272)
其他文章我没细看

**Comment by AmazingAng** [comment]
嗯 就是抄袭的

**Comment by caihuach** [comment]
我只是不想看到这种人标记“原创”，但你是作者你决定吧，辛苦了

**Comment by AmazingAng** [comment]
嗯 之前已经维权举报过很多了，继续举报。

**Comment by AmazingAng** [comment]
之后开个页面 大家可以上传抄袭的页面 社群成员可以一起举报

**Comment by XdpCs** [comment]
https://github.com/AmazingAng/WTF-Solidity/discussions/824
欢迎在下面提供链接 @caihuach
