### ISSUE TITLE
[emit Purchase error] [Class (38_NFTSwap)] Title（_order.price显示为0）

### ISSUE THREAD

**Issue by REBOA** [AmazingAng/WTF-Solidity#734]
### Details (细节)

按照NFTSwap.sol中给定的代码测试purchase函数，先删除order会导致释放Purchase事件中的_order.price显示为0。

应该将这两行代码互换位置吧：
delete nftList[_nftAddr][_tokenId]; // 删除order
// 释放Purchase事件
emit Purchase(msg.sender, _nftAddr, _tokenId, _order.price);

### Environment (环境)

Remix

### Are you willing to submit PR?(你愿意提交PR吗？)

- [ ] Yes I am willing to submit a PR!(是的我愿意)

**Comment by XdpCs** [comment]
I will fix it.

**Comment by XdpCs** [comment]
```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.8.2 <0.9.0;


contract Storage {
    struct Order {
        address owner;
        uint256 price;
    }
    Order[] orders;
    event DeleteOrder(address, uint256);

    
    function deleteOrder(uint256 index) public {
        Order storage o = orders[index];
        delete orders[index];
        emit DeleteOrder(o.owner, o.price);
    }

    function store(address owner, uint256 price) public returns (uint) {
        orders.push(Order(owner, price));
        return orders.length - 1;
    }
}
```

写了个类似的代码

<img width="728" alt="image" src="https://github.com/AmazingAng/WTF-Solidity/assets/72180730/44161908-7ca2-4f66-8cc1-2297ae3549dd">
