### ISSUE TITLE
第 4 讲 命名式返回

### ISSUE THREAD

**Issue by 0xZoomEye** [AmazingAng/WTF-Solidity#772]
### Details(细节)

原文是

我们可以在 `returns` 中标明返回变量的名称。Solidity 会初始化这些变量，并且自动返回这些**函数**的值，无需使用 `return`。

应该是

我们可以在 `returns` 中标明返回变量的名称。Solidity 会初始化这些变量，并且自动返回这些**变量**的值，无需使用 `return`。

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by linghuccc** [comment]
厉害，我看的时候都没发现，你可以提交一个 PR，题目就在 github 代码库里面

**Comment by linghuccc** [comment]
修改 https://github.com/AmazingAng/WTF-Solidity/blob/main/04_Return/readme.md 这个文件就可以了
