### ISSUE TITLE
Why is the code comment for Section 22 call in Japanese

### ISSUE THREAD

**Issue by baiyazi233** [AmazingAng/WTF-Solidity#791]
### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by AmazingAng** [comment]
估计是在翻译日文版的时候pr错了，今晚改过来

**Comment by AmazingAng** [comment]
已更新
https://github.com/AmazingAng/WTF-Solidity/blob/main/22_Call/Call.sol
