### ISSUE TITLE
[Feature]S08_ContractCheck示例代码中增加 GoodContractCheck 的示例

### ISSUE THREAD

**Issue by andOneBasketball** [AmazingAng/WTF-Solidity#792]
### Details(细节)

https://github.com/AmazingAng/WTF-Solidity/blob/main/S08_ContractCheck/ContractCheck.sol 中仅有漏洞合约的展示。虽然https://www.wtf.academy/docs/solidity-104/S08_ContractCheck/ 教程中讲解的非常清晰如何避免该漏洞，但示例代码中缺少安全合约的展示

### Motivation(动机)

让通过该项目熟悉 solidity 的开发者更快更好的掌握solidity 的技术栈

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by XdpCs** [comment]
i will fix it.

**Comment by XdpCs** [comment]
我暂时没有找到很好的解决方案，我参考了openzeppelin。
如果后期有的话，欢迎提交pr。

**Comment by andOneBasketball** [comment]
> 我暂时没有找到很好的解决方案，我参考了openzeppelin。 如果后期有的话，欢迎提交pr。 ref: https://github.com/OpenZeppelin/openzeppelin-contracts/pull/3945/files

好的，等我有空了来 fork 一下仓库提交个PR，一起看看我的想法是否能解决这个安全场景的问题
