### ISSUE TITLE
[Feature][30. Try Catch] Added `public` in try catch

### ISSUE THREAD

**Issue by gsangeryee** [AmazingAng/WTF-Solidity#800]
### Details(细节)

Emphasize that `try-catch` can only be used for `external` and `public` function.

### Motivation(动机)

Beginners may think that try catch can only be used in external functions.

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by smallfu6** [comment]
The intended meaning is that try-catch can only be used to catch calls to external functions and constructor functions when creating a contract.  This could lead to ambiguity in expression; it can be revised for clarity.

**Comment by smallfu6** [comment]
The intended meaning is that try-catch can only be used to catch calls to external functions,  and constructor functions when creating a contract. This could lead to ambiguity in expression; it can be revised for clarity.

**Comment by smallfu6** [comment]
The intended meaning is that try-catch can only be used to catch calls to external functions and the constructor function when creating a contract. This could lead to ambiguity in expression; it can be revised for clarity.

**Comment by XdpCs** [comment]
I will update it soon.
