### ISSUE TITLE
[Improvement][45_Timelock] question regarding visibility setting of changeAdmin function

### ISSUE THREAD

**Issue by smallfu6** [AmazingAng/WTF-Solidity#806]
### Description

In the Timelock contract, the changeAdmin function is currently set to public, and it uses the onlyTimelock modifier to ensure that only the contract itself can call this function. I believe it would be more appropriate to set the changeAdmin function to private.

```Solidity
/**
 * @dev 改变管理员地址，调用者必须是Timelock合约。
 */
function changeAdmin(address newAdmin) public onlyTimelock {
        admin = newAdmin;

        emit NewAdmin(newAdmin);
 }
```

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by XdpCs** [comment]
public onlyTimelock == private
I think `public onlyTimelock` will be clearer, `private` needs more info to explain why it is `private`.

**Comment by XdpCs** [comment]
If you have any questions, you can reopen this issue.
