### ISSUE TITLE
[Doc][14_Interface_en] Fix Typos in readme.md

### ISSUE THREAD

**Issue by ChenBingWei1201** [AmazingAng/WTF-Solidity#807]
### Details(细节)

1. There is a white space in the link so the hyperlink `abi-to-sol tool` doesn't display correctly in Markdown.
![image](https://github.com/user-attachments/assets/d87dad2b-5015-4784-b1ea-1f71a6ae9aad)
2. Here are two `tokenid`, but others are `tokenId`. I want to keep the variable's name consistent in the README.md.
![image](https://github.com/user-attachments/assets/4607b86c-8657-4979-84fe-0ccac2171f87)

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by XdpCs** [comment]
@ChenBingWei1201 Pr is merged, you can close the issue.
