### ISSUE TITLE
[Improvement][47_Upgrade] preventing invalid contract upgrade

### ISSUE THREAD

**Issue by smallfu6** [AmazingAng/WTF-Solidity#809]
### Description

In the upgrade function,  we can  add a check to prevent upgrading to the same implementation address. 
```solidity
require(implementation != newImplementation, "Can not upgrade to the same implementation");
```

The relevant code is as follows:

```solidity
// 升级函数，改变逻辑合约地址，只能由admin调用
function upgrade(address newImplementation) external {
        require(msg.sender == admin);
        require(implementation != newImplementation, "Can not upgrade to the same implementation");
        implementation = newImplementation;
}
```

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by eshumanohare** [comment]
hello @smallfu6 , I would like to take this issue. Please assign it to me with all the relevant paths.

**Comment by LewisY2** [comment]
Thank you

**Comment by XdpCs** [comment]
This code is just for teaching people to understand the upgrade logic.
