### ISSUE TITLE
[Doc][20_SendETH_en] Fix Typo in readme.md

### ISSUE THREAD

**Issue by ChenBingWei1201** [AmazingAng/WTF-Solidity#813]
### Details(细节)

If `send()` fails, the transaction will **not** be reverted.

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by XdpCs** [comment]
@ChenBingWei1201 Pr is merged, you can close the issue.
