### ISSUE TITLE
[Doc][ OnChain Transaction Debugging: 1. Tools ]  I found some broken links

### ISSUE THREAD

**Issue by Passi0n1** [AmazingAng/WTF-Solidity#815]
### Details(细节)

hi，I found some tool links in "OnChain Transaction Debugging: 1. Tools" are invalid. You can update or delete them.

The inaccessible links are as follows:
https://cruise.supremacy.team/
https://tx.eth.samczsun.com/
https://sig.eth.samczsun.com/

### Are you willing to submit a PR?(你愿意提交PR吗？)

- [X] Yes I am willing to submit a PR!(是的我愿意)

**Comment by XdpCs** [comment]
I will fix it.
