### ISSUE TITLE
[题目选项加载不出来] [4] 函数输出（标题）

### ISSUE THREAD

**Issue by lujiuqi** [AmazingAng/WTF-Solidity#839]
### Details (细节)

![image](https://github.com/user-attachments/assets/b6685606-57de-43c2-ade9-8b5b6734a81b)

### Are you willing to submit PR?(你愿意提交PR吗？)

- [ ] Yes I am willing to submit a PR!(是的我愿意)

**Comment by XdpCs** [comment]
![image](https://github.com/user-attachments/assets/7fead770-75d1-4cce-a267-ce230363723b)
请刷新一下页面或者查看一下自己的梯子
