### ISSUE TITLE
require和assert的gas消耗对比问题

### ISSUE THREAD

**Issue by edddyguo** [AmazingAng/WTF-Solidity#93]
理论上require的报错会将余下的gas返回给user，而assert会全部没收，而15_Error中实验结果，是assert比require更少的损耗，问题出在哪里

**Comment by AmazingAng** [comment]
这个不知道，你可以跑下代码试试看。

**Comment by MultiSuperK** [comment]
@edddyguo 可以用钱包连公链测试一下差异，remix提供的默认节点返回的gas应该是实际执行指令的gas cost，跟公链有差别

**Comment by edddyguo** [comment]
> 

我在相应的require和assert的下方加入了一个for循环100次的逻辑，测试结果和原来的一直，assert都是将剩下的gas返还给user了，考虑到编译器版本的问题，我用0.6.4的编译器也是同样的测试结果，不知道为啥和搜到的文档里面描述的不一样

**Comment by edddyguo** [comment]
> @edddyguo 可以用钱包连公链测试一下差异，remix提供的默认节点返回的gas应该是实际执行指令的gas cost，跟公链有差别

一直是用的rinkeby测试的

**Comment by CryptoRbtree** [comment]
Panic exceptions used to use the invalid opcode before Solidity 0.8.0, which consumed all gas available to the call.
https://docs.soliditylang.org/en/latest/control-structures.html#revert
感觉可以看下字节码指令是revert还是invalid

**Comment by Lisanaaa** [comment]
我深入研究了一下：
# Assert
`assert`关键字的底层`opcode`在`Solidity 8.0`之前都是[`INVALID`](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#af-invalid), 是会消耗所有的剩余gas的，然后将所有状态恢复到这个call之前
- **AF: INVALID**

On execution of any invalid operation, whether the designated INVALID opcode or simply an undefined opcode, all remaining gas is consumed and the state is reverted to the point immediately prior to the beginning of the current execution context.
![image](https://user-images.githubusercontent.com/28261876/194688119-47467a5f-c486-4855-9954-34642fb09280.png)

---
`assert`关键字的底层`opcode`在`Solidity 8.0`之后都是[`REVERT`](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion), 而REVERT opcode只是一个简单的内存操作, `revert(mem[ost:ost+len-1])`，剩余的gas是会返还的
- **A0-1: Memory Expansion**
An additional gas cost is paid by any operation that expands the memory that is in use. This memory expansion cost is dependent on the existing memory size and is 0 if the operation does not reference a memory address higher than the existing highest referenced memory address. A reference is any read, write, or other usage of memory (such as in a CALL).

![image](https://user-images.githubusercontent.com/28261876/194687719-0afd459c-e561-4b01-8bdb-ca95b7ffbbe8.png)

# Require
`Require`关键字的底层opcode不管在Solidity的哪个版本都是REVERT，因此都会返还剩余的gas
![image](https://user-images.githubusercontent.com/28261876/194688358-4000b892-132d-4206-8162-43802e1cb50f.png)
<img width="752" alt="image" src="https://user-images.githubusercontent.com/28261876/194688375-e3d14961-9dc5-4d0e-af56-a4ce920d25d7.png">


# Revert
`Revert` 关键字跟`Require`一样，会返还所有剩余的gas，可以自己去做实验

# Hightlight
以上讨论的topic都是`是否会返还剩余的gas`，已经执行过的语句（即报错之前的语句）所消耗的gas是不会返还的，因为这一块已经占用了矿工们（现在是POS Validator）的资源了，如果不收费就会造成有人无成本攻击Ethereum生态了。


***References***
- https://github.com/wolflo/evm-opcodes/blob/main/gas.md#af-invalid
- https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion
- https://docs.soliditylang.org/en/v0.8.7/control-structures.html?highlight=assert%20gas#panic-via-assert-and-error-via-require
- https://ethereum.org/en/developers/docs/evm/opcodes/

**Comment by AmazingAng** [comment]
> 我深入研究了一下：
> 
> # Assert
> `assert`关键字的底层`opcode`在`Solidity 8.0`之前都是[`INVALID`](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#af-invalid), 是会消耗所有的剩余gas的，然后将所有状态恢复到这个call之前
> 
> * **AF: INVALID**
> 
> On execution of any invalid operation, whether the designated INVALID opcode or simply an undefined opcode, all remaining gas is consumed and the state is reverted to the point immediately prior to the beginning of the current execution context. ![image](https://user-images.githubusercontent.com/28261876/194688119-47467a5f-c486-4855-9954-34642fb09280.png)
> 
> `assert`关键字的底层`opcode`在`Solidity 8.0`之后都是[`REVERT`](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion), 而REVERT opcode只是一个简单的内存操作, `revert(mem[ost:ost+len-1])`，剩余的gas是会返还的
> 
> * **A0-1: Memory Expansion**
>   An additional gas cost is paid by any operation that expands the memory that is in use. This memory expansion cost is dependent on the existing memory size and is 0 if the operation does not reference a memory address higher than the existing highest referenced memory address. A reference is any read, write, or other usage of memory (such as in a CALL).
> 
> ![image](https://user-images.githubusercontent.com/28261876/194687719-0afd459c-e561-4b01-8bdb-ca95b7ffbbe8.png)
> 
> # Require
> `Require`关键字的底层opcode不管在Solidity的哪个版本都是REVERT，因此都会返还剩余的gas ![image](https://user-images.githubusercontent.com/28261876/194688358-4000b892-132d-4206-8162-43802e1cb50f.png) <img alt="image" width="752" src="https://user-images.githubusercontent.com/28261876/194688375-e3d14961-9dc5-4d0e-af56-a4ce920d25d7.png">
> 
> # Revert
> `Revert` 关键字跟`Require`一样，会返还所有剩余的gas，可以自己去做实验
> 
> # Hightlight
> 以上讨论的topic都是`是否会返还剩余的gas`，已经执行过的语句（即报错之前的语句）所消耗的gas是不会返还的，因为这一块已经占用了矿工们（现在是POS Validator）的资源了，如果不收费就会造成有人无成本攻击Ethereum生态了。
> 
> _**References**_
> 
> * https://github.com/wolflo/evm-opcodes/blob/main/gas.md#af-invalid
> * https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion
> * https://docs.soliditylang.org/en/v0.8.7/control-structures.html?highlight=assert%20gas#panic-via-assert-and-error-via-require
> * https://ethereum.org/en/developers/docs/evm/opcodes/

wow 详细

**Comment by dukedaily** [comment]
> 我深入研究了一下：
> 
> # Assert
> `assert`关键字的底层`opcode`在`Solidity 8.0`之前都是[`INVALID`](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#af-invalid), 是会消耗所有的剩余gas的，然后将所有状态恢复到这个call之前
> 
> * **AF: INVALID**
> 
> On execution of any invalid operation, whether the designated INVALID opcode or simply an undefined opcode, all remaining gas is consumed and the state is reverted to the point immediately prior to the beginning of the current execution context. ![image](https://user-images.githubusercontent.com/28261876/194688119-47467a5f-c486-4855-9954-34642fb09280.png)
> 
> `assert`关键字的底层`opcode`在`Solidity 8.0`之后都是[`REVERT`](https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion), 而REVERT opcode只是一个简单的内存操作, `revert(mem[ost:ost+len-1])`，剩余的gas是会返还的
> 
> * **A0-1: Memory Expansion**
>   An additional gas cost is paid by any operation that expands the memory that is in use. This memory expansion cost is dependent on the existing memory size and is 0 if the operation does not reference a memory address higher than the existing highest referenced memory address. A reference is any read, write, or other usage of memory (such as in a CALL).
> 
> ![image](https://user-images.githubusercontent.com/28261876/194687719-0afd459c-e561-4b01-8bdb-ca95b7ffbbe8.png)
> 
> # Require
> `Require`关键字的底层opcode不管在Solidity的哪个版本都是REVERT，因此都会返还剩余的gas ![image](https://user-images.githubusercontent.com/28261876/194688358-4000b892-132d-4206-8162-43802e1cb50f.png) <img alt="image" width="752" src="https://user-images.githubusercontent.com/28261876/194688375-e3d14961-9dc5-4d0e-af56-a4ce920d25d7.png">
> 
> # Revert
> `Revert` 关键字跟`Require`一样，会返还所有剩余的gas，可以自己去做实验
> 
> # Hightlight
> 以上讨论的topic都是`是否会返还剩余的gas`，已经执行过的语句（即报错之前的语句）所消耗的gas是不会返还的，因为这一块已经占用了矿工们（现在是POS Validator）的资源了，如果不收费就会造成有人无成本攻击Ethereum生态了。
> 
> _**References**_
> 
> * https://github.com/wolflo/evm-opcodes/blob/main/gas.md#af-invalid
> * https://github.com/wolflo/evm-opcodes/blob/main/gas.md#a0-1-memory-expansion
> * https://docs.soliditylang.org/en/v0.8.7/control-structures.html?highlight=assert%20gas#panic-via-assert-and-error-via-require
> * https://ethereum.org/en/developers/docs/evm/opcodes/

bravo!

**Comment by Lisanaaa** [comment]
# Note
另外，在`REVERT` opcode被正式引入之前，所有rollback操作只能通过`INVALID` opcode来执行，痛点就是虽然rollback了但仍然要消耗掉所有剩余的gas，资本效率非常低。且那个时候Solidity连`Require`和`Revert`关键字都还没有
# Time logs

- 2016年8月22日 [nmushegian](https://github.com/nmushegian) 在这个[PR](https://github.com/ethereum/EIPs/issues/140)中提出想引入一个新的opcode为`REVERT`
- 2017年2月7号 [axic](https://github.com/axic) 正式编写 [EIP-140](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-140.md)
- 2017年3月16正式发布[Solidity `0.4.10`](https://github.com/ethereum/solidity/releases/tag/v0.4.10) 版本，一次性加入了`Require`关键字，`Revert`关键字，`REVERT` opcode的编译支持。
- 2017年9月14日发布[EVM Megara (v1.7.0)](https://github.com/ethereum/go-ethereum/releases/tag/v1.7.0)，支持`REVERT` opcode。

**BTW，从这里我们可以看出来好像是Solidity语言先支持，然后EVM再支持，这个有点违反我的直觉了，没想通。**
---

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/28261876/194700170-d8cca6bc-f43d-4af4-972f-e6bed6bc9fab.png">
<img width="1159" alt="image" src="https://user-images.githubusercontent.com/28261876/194700424-5ed0fd9c-4d35-4523-be89-0e82a510318a.png">
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/28261876/194700033-d6c6da82-7285-4571-b700-7d24aaa4da15.png">
<img width="1349" alt="image" src="https://user-images.githubusercontent.com/28261876/194700824-95f02f28-6d16-4379-9071-3f279e10c5b0.png">

*References*
- https://github.com/ethereum/EIPs/issues/140
- https://github.com/ethereum/EIPs/pull/206
- https://github.com/ethereum/solidity/releases/tag/v0.4.10
- https://github.com/ethereum/go-ethereum/releases/tag/v1.7.0
